language: ruby
rvm:
  - 2.3.1
cache: bundler
env:
  - RAILS_ENV=test
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
bundler_args: --without development profile
notifications:
  email:
    on_success: change
    on_failure: always
